-- ============================================================================
-- CoachFlow — starter exercise library.
-- Additive. Does not edit 0001–0013, disable RLS, or change workout policies.
-- Shared rows use trainer_id null. Existing shared names are left as they are.
-- ============================================================================

insert into public.exercises (name, category, muscle_group, equipment, instructions, is_custom, trainer_id)
select seed.name, seed.category, seed.muscle_group, seed.equipment, seed.instructions, false, null
from (
  values
  ('Incline Bench Press', 'Strength', 'Chest', 'Barbell', 'Lower the bar to the upper chest, then press to lockout.'),
  ('Decline Bench Press', 'Strength', 'Chest', 'Barbell', 'Lower the bar to the lower chest, then press to lockout.'),
  ('Dumbbell Bench Press', 'Strength', 'Chest', 'Dumbbell', 'Lower the dumbbells to chest level, then press up.'),
  ('Incline Dumbbell Press', 'Strength', 'Chest', 'Dumbbell', 'Press the dumbbells from the upper chest to lockout.'),
  ('Dumbbell Fly', 'Strength', 'Chest', 'Dumbbell', 'Open the arms with a soft elbow, then squeeze the chest to close.'),
  ('Cable Fly', 'Strength', 'Chest', 'Cable', 'Bring the handles together in front of the chest.'),
  ('Incline Cable Fly', 'Strength', 'Chest', 'Cable', 'Set the cables low and bring the handles up together.'),
  ('Chest Dip', 'Strength', 'Chest', 'Bodyweight', 'Lean forward and lower until the shoulders are below the elbows.'),
  ('Machine Chest Press', 'Strength', 'Chest', 'Machine', 'Press the handles away without locking the shoulders forward.'),
  ('Pec Deck', 'Strength', 'Chest', 'Machine', 'Bring the pads together in front of the chest.'),
  ('Close-Grip Push-up', 'Strength', 'Chest', 'Bodyweight', 'Hands close under the chest. Lower and press back up.'),
  ('Chin-up', 'Strength', 'Back', 'Bodyweight', 'Pull the chest toward the bar with an underhand grip.'),
  ('Seated Cable Row', 'Strength', 'Back', 'Cable', 'Sit tall and pull the handle to the lower ribs.'),
  ('Dumbbell Row', 'Strength', 'Back', 'Dumbbell', 'Support one hand and pull the dumbbell to the hip.'),
  ('Chest-Supported Row', 'Strength', 'Back', 'Dumbbell', 'Lie face down and pull the dumbbells to the ribs.'),
  ('Face Pull', 'Strength', 'Shoulders', 'Cable', 'Pull the rope toward the face with the elbows high.'),
  ('Straight-Arm Pulldown', 'Strength', 'Back', 'Cable', 'Keep the arms straight and pull the bar to the thighs.'),
  ('Inverted Row', 'Strength', 'Back', 'Bodyweight', 'Body straight under a bar. Pull the chest to the bar.'),
  ('Machine Row', 'Strength', 'Back', 'Machine', 'Pull the handles to the ribs and return with control.'),
  ('Meadows Row', 'Strength', 'Back', 'Barbell', 'One end of the bar. Pull toward the hip.'),
  ('Rack Pull', 'Strength', 'Back', 'Barbell', 'Pull from the pins to a standing lockout.'),
  ('Pendlay Row', 'Strength', 'Back', 'Barbell', 'Bar starts on the floor each rep. Pull to the lower ribs.'),
  ('Neutral-Grip Pull-up', 'Strength', 'Back', 'Bodyweight', 'Palms facing. Pull the chest toward the handles.'),
  ('Dumbbell Shoulder Press', 'Strength', 'Shoulders', 'Dumbbell', 'Press the dumbbells from shoulder height to lockout.'),
  ('Arnold Press', 'Strength', 'Shoulders', 'Dumbbell', 'Rotate the palms out as you press overhead.'),
  ('Lateral Raise', 'Strength', 'Shoulders', 'Dumbbell', 'Raise the arms out to shoulder height.'),
  ('Front Raise', 'Strength', 'Shoulders', 'Dumbbell', 'Raise the dumbbells in front to shoulder height.'),
  ('Rear Delt Fly', 'Strength', 'Shoulders', 'Dumbbell', 'Hinge forward and open the arms out to the sides.'),
  ('Upright Row', 'Strength', 'Shoulders', 'Barbell', 'Pull the bar up along the body to chest height.'),
  ('Push Press', 'Strength', 'Shoulders', 'Barbell', 'Dip slightly, then drive the bar overhead.'),
  ('Machine Shoulder Press', 'Strength', 'Shoulders', 'Machine', 'Press the handles overhead without shrugging.'),
  ('Cable Lateral Raise', 'Strength', 'Shoulders', 'Cable', 'Raise the arm out to shoulder height.'),
  ('Landmine Press', 'Strength', 'Shoulders', 'Barbell', 'Press one end of the bar up and away from the shoulder.'),
  ('Band Pull-Apart', 'Strength', 'Shoulders', 'Resistance band', 'Pull the band apart until the hands are in line with the shoulders.'),
  ('Z-Press', 'Strength', 'Shoulders', 'Barbell', 'Sit on the floor and press the bar overhead.'),
  ('Barbell Curl', 'Strength', 'Biceps', 'Barbell', 'Curl the bar without swinging the torso.'),
  ('Dumbbell Curl', 'Strength', 'Biceps', 'Dumbbell', 'Curl the dumbbells and lower with control.'),
  ('Hammer Curl', 'Strength', 'Biceps', 'Dumbbell', 'Palms face each other. Curl without swinging.'),
  ('Incline Dumbbell Curl', 'Strength', 'Biceps', 'Dumbbell', 'Lie on an incline and curl from a stretched position.'),
  ('Preacher Curl', 'Strength', 'Biceps', 'Barbell', 'Upper arms on the pad. Curl and lower fully.'),
  ('Cable Curl', 'Strength', 'Biceps', 'Cable', 'Curl the handle and keep the elbows still.'),
  ('Concentration Curl', 'Strength', 'Biceps', 'Dumbbell', 'Brace the elbow on the thigh and curl.'),
  ('EZ-Bar Curl', 'Strength', 'Biceps', 'Barbell', 'Curl the EZ-bar without leaning back.'),
  ('Spider Curl', 'Strength', 'Biceps', 'Dumbbell', 'Chest on an incline bench. Curl from a hanging start.'),
  ('Triceps Pushdown', 'Strength', 'Triceps', 'Cable', 'Push the handle down until the elbows are straight.'),
  ('Skull Crusher', 'Strength', 'Triceps', 'Barbell', 'Lower the bar toward the forehead, then extend the elbows.'),
  ('Overhead Triceps Extension', 'Strength', 'Triceps', 'Dumbbell', 'Lower the dumbbell behind the head, then extend.'),
  ('Dip', 'Strength', 'Triceps', 'Bodyweight', 'Stay upright and lower until the elbows are about 90 degrees.'),
  ('Close-Grip Bench Press', 'Strength', 'Triceps', 'Barbell', 'Hands just inside shoulder width. Press to lockout.'),
  ('Dumbbell Kickback', 'Strength', 'Triceps', 'Dumbbell', 'Upper arm still. Extend the elbow back.'),
  ('Cable Overhead Extension', 'Strength', 'Triceps', 'Cable', 'Extend the elbows overhead from a bent position.'),
  ('Bench Dip', 'Strength', 'Triceps', 'Bodyweight', 'Hands on a bench. Lower the body, then press up.'),
  ('JM Press', 'Strength', 'Triceps', 'Barbell', 'Lower the bar toward the chin and press back up.'),
  ('Wrist Curl', 'Strength', 'Forearms', 'Dumbbell', 'Palms up. Curl the wrists.'),
  ('Reverse Wrist Curl', 'Strength', 'Forearms', 'Dumbbell', 'Palms down. Extend the wrists.'),
  ('Farmers Carry', 'Strength', 'Forearms', 'Dumbbell', 'Walk tall while holding a heavy weight in each hand.'),
  ('Dead Hang', 'Strength', 'Forearms', 'Bodyweight', 'Hang from a bar with the shoulders relaxed.'),
  ('Suitcase Carry', 'Strength', 'Forearms', 'Dumbbell', 'Walk tall holding a weight in one hand.'),
  ('Front Squat', 'Strength', 'Quads', 'Barbell', 'Bar at the shoulders. Sit down, then stand.'),
  ('Goblet Squat', 'Strength', 'Quads', 'Dumbbell', 'Hold one dumbbell at the chest and squat down.'),
  ('Leg Press', 'Strength', 'Quads', 'Machine', 'Lower until the knees are bent, then press away.'),
  ('Leg Extension', 'Strength', 'Quads', 'Machine', 'Extend the knees, then lower with control.'),
  ('Bulgarian Split Squat', 'Strength', 'Quads', 'Dumbbell', 'Rear foot elevated. Lower the back knee, then stand.'),
  ('Walking Lunge', 'Strength', 'Quads', 'Dumbbell', 'Step forward, lower, and continue walking.'),
  ('Hack Squat', 'Strength', 'Quads', 'Machine', 'Shoulders under the pads. Squat and press back up.'),
  ('Step-up', 'Strength', 'Quads', 'Dumbbell', 'Step onto a box and stand tall, then step down.'),
  ('Sissy Squat', 'Strength', 'Quads', 'Bodyweight', 'Knees travel forward as the torso leans back.'),
  ('Reverse Lunge', 'Strength', 'Quads', 'Dumbbell', 'Step backward, lower, and return to standing.'),
  ('Box Squat', 'Strength', 'Quads', 'Barbell', 'Sit back to a box, then stand.'),
  ('Wall Sit', 'Strength', 'Quads', 'Bodyweight', 'Back on the wall, knees bent, and hold.'),
  ('Dumbbell Romanian Deadlift', 'Strength', 'Hamstrings', 'Dumbbell', 'Soft knees. Push the hips back and stand tall.'),
  ('Leg Curl', 'Strength', 'Hamstrings', 'Machine', 'Curl the heels toward the glutes.'),
  ('Seated Leg Curl', 'Strength', 'Hamstrings', 'Machine', 'Curl the pad down, then return slowly.'),
  ('Good Morning', 'Strength', 'Hamstrings', 'Barbell', 'Bar on the back. Hinge forward and stand up.'),
  ('Nordic Hamstring Curl', 'Strength', 'Hamstrings', 'Bodyweight', 'Lower the body forward and pull back with the hamstrings.'),
  ('Sumo Deadlift', 'Strength', 'Hamstrings', 'Barbell', 'Wide stance. Push the floor away and stand tall.'),
  ('Glute Bridge', 'Strength', 'Glutes', 'Bodyweight', 'Drive the hips up and squeeze the glutes.'),
  ('Cable Pull-Through', 'Strength', 'Glutes', 'Cable', 'Hinge back, then drive the hips forward.'),
  ('Hip Abduction', 'Strength', 'Glutes', 'Machine', 'Press the legs apart and return with control.'),
  ('Hip Adduction', 'Strength', 'Glutes', 'Machine', 'Bring the legs together and return with control.'),
  ('Cable Kickback', 'Strength', 'Glutes', 'Cable', 'Kick the heel back without arching the lower back.'),
  ('Frog Pump', 'Strength', 'Glutes', 'Bodyweight', 'Soles together. Drive the hips up.'),
  ('Single-Leg Hip Thrust', 'Strength', 'Glutes', 'Bodyweight', 'One foot down. Drive that hip to full extension.'),
  ('Standing Calf Raise', 'Strength', 'Calves', 'Machine', 'Rise onto the toes and lower the heels.'),
  ('Seated Calf Raise', 'Strength', 'Calves', 'Machine', 'Press up onto the toes from a seated position.'),
  ('Donkey Calf Raise', 'Strength', 'Calves', 'Machine', 'Hinge forward and rise onto the toes.'),
  ('Single-Leg Calf Raise', 'Strength', 'Calves', 'Bodyweight', 'Stand on one foot and rise onto the toes.'),
  ('Side Plank', 'Core', 'Core', 'Bodyweight', 'Elbow under the shoulder. Hold a straight line.'),
  ('Dead Bug', 'Core', 'Core', 'Bodyweight', 'Lower the opposite arm and leg while the back stays down.'),
  ('Hanging Leg Raise', 'Core', 'Core', 'Bodyweight', 'Hang and lift the legs without swinging.'),
  ('Cable Crunch', 'Core', 'Core', 'Cable', 'Kneel and curl the ribs toward the hips.'),
  ('Russian Twist', 'Core', 'Core', 'Bodyweight', 'Rotate the torso side to side with the chest up.'),
  ('Ab Wheel Rollout', 'Core', 'Core', 'No equipment', 'Roll forward and pull back without letting the hips sag.'),
  ('Bicycle Crunch', 'Core', 'Core', 'Bodyweight', 'Rotate the elbow toward the opposite knee.'),
  ('Mountain Climber', 'Conditioning', 'Core', 'Bodyweight', 'Hands planted. Drive the knees in one at a time.'),
  ('Pallof Press', 'Core', 'Core', 'Cable', 'Press the handle out and resist the rotation.'),
  ('Hollow Hold', 'Core', 'Core', 'Bodyweight', 'Lower back down, arms and legs extended, and hold.'),
  ('Bird Dog', 'Core', 'Core', 'Bodyweight', 'Reach the opposite arm and leg while the hips stay level.'),
  ('Cable Woodchop', 'Core', 'Core', 'Cable', 'Rotate the handle from high to low across the body.'),
  ('Kettlebell Swing', 'Strength', 'Full body', 'Kettlebell', 'Hinge and swing the bell to chest height.'),
  ('Thruster', 'Strength', 'Full body', 'Dumbbell', 'Squat, then press the weights overhead.'),
  ('Burpee', 'Conditioning', 'Full body', 'Bodyweight', 'Drop to the floor, stand, and jump.'),
  ('Clean', 'Strength', 'Full body', 'Barbell', 'Pull the bar from the floor to the shoulders.'),
  ('Power Clean', 'Strength', 'Full body', 'Barbell', 'Pull the bar and catch it on the shoulders.'),
  ('Dumbbell Snatch', 'Strength', 'Full body', 'Dumbbell', 'Pull one dumbbell from the floor to overhead.'),
  ('Turkish Get-up', 'Strength', 'Full body', 'Kettlebell', 'Move from lying to standing while the weight stays overhead.'),
  ('Bear Crawl', 'Conditioning', 'Full body', 'Bodyweight', 'Crawl forward with the knees just off the floor.'),
  ('Rowing', 'Conditioning', 'Full body', 'Cardio', 'Drive with the legs, then pull the handle to the ribs.'),
  ('Cycling', 'Conditioning', 'Quads', 'Cardio', 'Pedal at a steady pace.'),
  ('Treadmill Run', 'Conditioning', 'Full body', 'Cardio', 'Run or walk at the chosen pace.'),
  ('Assault Bike', 'Conditioning', 'Full body', 'Cardio', 'Push and pull the handles while pedaling.'),
  ('Jump Rope', 'Conditioning', 'Calves', 'Cardio', 'Stay tall and turn the rope with the wrists.'),
  ('Sled Push', 'Conditioning', 'Full body', 'No equipment', 'Lean into the sled and drive it forward.'),
  ('Battle Ropes', 'Conditioning', 'Shoulders', 'No equipment', 'Make waves with both arms.'),
  ('Stair Climber', 'Conditioning', 'Quads', 'Cardio', 'Step continuously without leaning on the rails.'),
  ('SkiErg', 'Conditioning', 'Full body', 'Cardio', 'Pull the handles down by driving the arms and hips.'),
  ('Jumping Jack', 'Conditioning', 'Full body', 'Bodyweight', 'Jump the feet out as the arms go overhead.'),
  ('Worlds Greatest Stretch', 'Mobility', 'Full body', 'No equipment', 'Lunge, reach the same-side hand down, then rotate the other arm up.'),
  ('Cat-Cow', 'Mobility', 'Back', 'No equipment', 'Round the back, then gently arch it.'),
  ('90/90 Hip Switch', 'Mobility', 'Hips', 'No equipment', 'Sit in 90/90 and rotate both knees to the other side.'),
  ('Couch Stretch', 'Mobility', 'Hips', 'No equipment', 'Rear knee down and hip extended. Hold tall.'),
  ('Thoracic Rotation', 'Mobility', 'Back', 'No equipment', 'Rotate the upper back while the hips stay still.'),
  ('Downward Dog', 'Mobility', 'Full body', 'No equipment', 'Hips high, heels toward the floor, and a long spine.'),
  ('Shoulder CARs', 'Mobility', 'Shoulders', 'No equipment', 'Make a slow full circle with the arm.'),
  ('Hip Flexor Stretch', 'Mobility', 'Hips', 'No equipment', 'Half-kneel and shift the hips forward.'),
  ('Hip Airplane', 'Mobility', 'Hips', 'No equipment', 'Stand on one leg and rotate the hips open, then closed.')
) as seed(name, category, muscle_group, equipment, instructions)
where not exists (
  select 1
  from public.exercises e
  where e.trainer_id is null
    and lower(e.name) = lower(seed.name)
);
